//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.07 at 12:38:15 PM EET 
//


package Function.Model.xml;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EquationData }
     * 
     */
    public EquationData createEquationData() {
        return new EquationData();
    }

    /**
     * Create an instance of {@link EquationData.Points }
     * 
     */
    public EquationData.Points createEquationDataPoints() {
        return new EquationData.Points();
    }

    /**
     * Create an instance of {@link EquationData.Coefs }
     * 
     */
    public EquationData.Coefs createEquationDataCoefs() {
        return new EquationData.Coefs();
    }

    /**
     * Create an instance of {@link EquationData.Points.XYCoef }
     * 
     */
    public EquationData.Points.XYCoef createEquationDataPointsXYCoef() {
        return new EquationData.Points.XYCoef();
    }

    /**
     * Create an instance of {@link EquationData.Coefs.Coef }
     * 
     */
    public EquationData.Coefs.Coef createEquationDataCoefsCoef() {
        return new EquationData.Coefs.Coef();
    }

}
